[2025-05-21T14:59:02.461+0000] {processor.py:186} INFO - Started process (PID=56) to work on /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T14:59:02.462+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taxi_data_loader.py for tasks to queue
[2025-05-21T14:59:02.464+0000] {logging_mixin.py:190} INFO - [2025-05-21T14:59:02.464+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T14:59:02.490+0000] {logging_mixin.py:190} INFO - [2025-05-21T14:59:02.485+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taxi_data_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taxi_data_loader.py", line 4, in <module>
    from scripts.gcs_to_bq_loader import load_csv_to_bq
ModuleNotFoundError: No module named 'scripts'
[2025-05-21T14:59:02.492+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T14:59:02.524+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taxi_data_loader.py took 0.068 seconds
[2025-05-21T14:59:32.649+0000] {processor.py:186} INFO - Started process (PID=66) to work on /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T14:59:32.650+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taxi_data_loader.py for tasks to queue
[2025-05-21T14:59:32.652+0000] {logging_mixin.py:190} INFO - [2025-05-21T14:59:32.651+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T14:59:32.665+0000] {logging_mixin.py:190} INFO - [2025-05-21T14:59:32.662+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taxi_data_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taxi_data_loader.py", line 4, in <module>
    from scripts.gcs_to_bq_loader import load_csv_to_bq
ModuleNotFoundError: No module named 'scripts'
[2025-05-21T14:59:32.666+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T14:59:32.685+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taxi_data_loader.py took 0.039 seconds
[2025-05-21T15:00:03.013+0000] {processor.py:186} INFO - Started process (PID=76) to work on /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:00:03.014+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taxi_data_loader.py for tasks to queue
[2025-05-21T15:00:03.017+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:00:03.016+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:00:03.033+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:00:03.028+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taxi_data_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taxi_data_loader.py", line 4, in <module>
    from scripts.gcs_to_bq_loader import load_csv_to_bq
ModuleNotFoundError: No module named 'scripts'
[2025-05-21T15:00:03.034+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:00:03.230+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taxi_data_loader.py took 0.224 seconds
[2025-05-21T15:00:33.451+0000] {processor.py:186} INFO - Started process (PID=86) to work on /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:00:33.452+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taxi_data_loader.py for tasks to queue
[2025-05-21T15:00:33.454+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:00:33.454+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:00:33.469+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:00:33.465+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taxi_data_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taxi_data_loader.py", line 4, in <module>
    from scripts.gcs_to_bq_loader import load_csv_to_bq
ModuleNotFoundError: No module named 'scripts'
[2025-05-21T15:00:33.470+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:00:33.488+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taxi_data_loader.py took 0.041 seconds
[2025-05-21T15:00:59.655+0000] {processor.py:186} INFO - Started process (PID=97) to work on /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:00:59.656+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taxi_data_loader.py for tasks to queue
[2025-05-21T15:00:59.658+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:00:59.658+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:00:59.680+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:00:59.677+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taxi_data_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taxi_data_loader.py", line 6, in <module>
    sys.path.append('/opt/airflow/scripts')
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2025-05-21T15:00:59.682+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:00:59.710+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taxi_data_loader.py took 0.059 seconds
[2025-05-21T15:01:14.174+0000] {processor.py:186} INFO - Started process (PID=109) to work on /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:01:14.175+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taxi_data_loader.py for tasks to queue
[2025-05-21T15:01:14.176+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:01:14.176+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:01:14.200+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:01:14.195+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taxi_data_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taxi_data_loader.py", line 5, in <module>
    sys.path.append('/opt/airflow/scripts')
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2025-05-21T15:01:14.202+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:01:14.248+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taxi_data_loader.py took 0.078 seconds
[2025-05-21T15:01:17.296+0000] {processor.py:186} INFO - Started process (PID=110) to work on /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:01:17.297+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taxi_data_loader.py for tasks to queue
[2025-05-21T15:01:17.300+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:01:17.300+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:01:17.319+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:01:17.316+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taxi_data_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taxi_data_loader.py", line 5, in <module>
    sys.path.append('/opt/airflow/scripts')
    ^^^
NameError: name 'sys' is not defined. Did you forget to import 'sys'
[2025-05-21T15:01:17.321+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:01:17.339+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taxi_data_loader.py took 0.047 seconds
[2025-05-21T15:01:31.408+0000] {processor.py:186} INFO - Started process (PID=111) to work on /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:01:31.409+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taxi_data_loader.py for tasks to queue
[2025-05-21T15:01:31.411+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:01:31.411+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:01:32.163+0000] {processor.py:925} INFO - DAG(s) 'dag_gcs_to_bq_loader' retrieved from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:01:32.367+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:01:32.365+0000] {override.py:1930} INFO - Created Permission View: can read on DAG:dag_gcs_to_bq_loader
[2025-05-21T15:01:32.443+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:01:32.442+0000] {override.py:1930} INFO - Created Permission View: can edit on DAG:dag_gcs_to_bq_loader
[2025-05-21T15:01:32.476+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:01:32.476+0000] {override.py:1930} INFO - Created Permission View: can delete on DAG:dag_gcs_to_bq_loader
[2025-05-21T15:01:32.516+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:01:32.516+0000] {override.py:1930} INFO - Created Permission View: can read on DAG Run:dag_gcs_to_bq_loader
[2025-05-21T15:01:32.543+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:01:32.542+0000] {override.py:1930} INFO - Created Permission View: can delete on DAG Run:dag_gcs_to_bq_loader
[2025-05-21T15:01:32.576+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:01:32.576+0000] {override.py:1930} INFO - Created Permission View: menu access on DAG Run:dag_gcs_to_bq_loader
[2025-05-21T15:01:32.610+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:01:32.609+0000] {override.py:1930} INFO - Created Permission View: can create on DAG Run:dag_gcs_to_bq_loader
[2025-05-21T15:01:32.610+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:01:32.610+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-21T15:01:32.621+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:01:32.621+0000] {dag.py:3262} INFO - Creating ORM DAG for dag_gcs_to_bq_loader
[2025-05-21T15:01:32.622+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:01:32.622+0000] {dag.py:4180} INFO - Setting next_dagrun for dag_gcs_to_bq_loader to None, run_after=None
[2025-05-21T15:01:32.734+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taxi_data_loader.py took 1.330 seconds
[2025-05-21T15:02:00.328+0000] {processor.py:186} INFO - Started process (PID=122) to work on /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:02:00.329+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taxi_data_loader.py for tasks to queue
[2025-05-21T15:02:00.331+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:02:00.331+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:02:00.890+0000] {processor.py:925} INFO - DAG(s) 'dag_gcs_to_bq_loader' retrieved from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:02:00.899+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:02:00.898+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-21T15:02:00.909+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:02:00.908+0000] {dag.py:4180} INFO - Setting next_dagrun for dag_gcs_to_bq_loader to None, run_after=None
[2025-05-21T15:02:00.997+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taxi_data_loader.py took 0.673 seconds
[2025-05-21T15:02:31.535+0000] {processor.py:186} INFO - Started process (PID=135) to work on /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:02:31.536+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taxi_data_loader.py for tasks to queue
[2025-05-21T15:02:31.537+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:02:31.537+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:02:32.055+0000] {processor.py:925} INFO - DAG(s) 'dag_gcs_to_bq_loader' retrieved from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:02:32.147+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:02:32.147+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-21T15:02:32.167+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:02:32.167+0000] {dag.py:4180} INFO - Setting next_dagrun for dag_gcs_to_bq_loader to None, run_after=None
[2025-05-21T15:02:32.213+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taxi_data_loader.py took 0.682 seconds
[2025-05-21T15:02:56.428+0000] {processor.py:186} INFO - Started process (PID=144) to work on /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:02:56.429+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taxi_data_loader.py for tasks to queue
[2025-05-21T15:02:56.431+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:02:56.431+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:02:57.079+0000] {processor.py:925} INFO - DAG(s) 'dag_gcs_to_bq_loader' retrieved from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:02:57.092+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:02:57.090+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-21T15:02:57.105+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:02:57.105+0000] {dag.py:4180} INFO - Setting next_dagrun for dag_gcs_to_bq_loader to None, run_after=None
[2025-05-21T15:02:57.178+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taxi_data_loader.py took 0.754 seconds
[2025-05-21T15:03:27.486+0000] {processor.py:186} INFO - Started process (PID=160) to work on /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:03:27.487+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taxi_data_loader.py for tasks to queue
[2025-05-21T15:03:27.489+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:03:27.489+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:03:28.011+0000] {processor.py:925} INFO - DAG(s) 'dag_gcs_to_bq_loader' retrieved from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:03:28.100+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:03:28.099+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-21T15:03:28.109+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:03:28.109+0000] {dag.py:4180} INFO - Setting next_dagrun for dag_gcs_to_bq_loader to None, run_after=None
[2025-05-21T15:03:28.161+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taxi_data_loader.py took 0.679 seconds
[2025-05-21T15:03:58.412+0000] {processor.py:186} INFO - Started process (PID=171) to work on /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:03:58.412+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taxi_data_loader.py for tasks to queue
[2025-05-21T15:03:58.414+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:03:58.414+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:03:59.026+0000] {processor.py:925} INFO - DAG(s) 'dag_gcs_to_bq_loader' retrieved from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:03:59.045+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:03:59.045+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-21T15:03:59.056+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:03:59.056+0000] {dag.py:4180} INFO - Setting next_dagrun for dag_gcs_to_bq_loader to None, run_after=None
[2025-05-21T15:03:59.089+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taxi_data_loader.py took 0.682 seconds
[2025-05-21T15:04:29.380+0000] {processor.py:186} INFO - Started process (PID=182) to work on /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:04:29.380+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taxi_data_loader.py for tasks to queue
[2025-05-21T15:04:29.383+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:04:29.383+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:04:29.955+0000] {processor.py:925} INFO - DAG(s) 'dag_gcs_to_bq_loader' retrieved from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:04:29.976+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:04:29.975+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-21T15:04:29.986+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:04:29.986+0000] {dag.py:4180} INFO - Setting next_dagrun for dag_gcs_to_bq_loader to None, run_after=None
[2025-05-21T15:04:30.023+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taxi_data_loader.py took 0.648 seconds
[2025-05-21T15:05:00.259+0000] {processor.py:186} INFO - Started process (PID=193) to work on /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:05:00.260+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taxi_data_loader.py for tasks to queue
[2025-05-21T15:05:00.262+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:05:00.261+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:05:00.829+0000] {processor.py:925} INFO - DAG(s) 'dag_gcs_to_bq_loader' retrieved from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:05:00.848+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:05:00.848+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-05-21T15:05:00.861+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:05:00.861+0000] {dag.py:4180} INFO - Setting next_dagrun for dag_gcs_to_bq_loader to None, run_after=None
[2025-05-21T15:05:00.926+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taxi_data_loader.py took 0.671 seconds
[2025-05-21T15:05:15.537+0000] {processor.py:186} INFO - Started process (PID=204) to work on /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:05:15.538+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taxi_data_loader.py for tasks to queue
[2025-05-21T15:05:15.540+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:05:15.540+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:05:19.587+0000] {logging_mixin.py:190} INFO - ✅ Loaded gs://jdeol003-bucket/capstone3_hafizh/taxi_zone_lookup.csv into purwadika.jcdeol3_capstone3_hafizh.taxi_zone
[2025-05-21T15:05:19.592+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:05:19.588+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taxi_data_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taxi_data_loader.py", line 28, in <module>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-05-21T15:05:19.593+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:05:19.625+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taxi_data_loader.py took 4.092 seconds
[2025-05-21T15:05:49.860+0000] {processor.py:186} INFO - Started process (PID=220) to work on /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:05:49.860+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taxi_data_loader.py for tasks to queue
[2025-05-21T15:05:49.862+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:05:49.862+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:05:53.124+0000] {logging_mixin.py:190} INFO - ✅ Loaded gs://jdeol003-bucket/capstone3_hafizh/taxi_zone_lookup.csv into purwadika.jcdeol3_capstone3_hafizh.taxi_zone
[2025-05-21T15:05:53.130+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:05:53.126+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taxi_data_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taxi_data_loader.py", line 28, in <module>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-05-21T15:05:53.130+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:05:53.148+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taxi_data_loader.py took 3.293 seconds
[2025-05-21T15:06:23.384+0000] {processor.py:186} INFO - Started process (PID=231) to work on /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:06:23.385+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taxi_data_loader.py for tasks to queue
[2025-05-21T15:06:23.386+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:06:23.386+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:06:27.363+0000] {logging_mixin.py:190} INFO - ✅ Loaded gs://jdeol003-bucket/capstone3_hafizh/taxi_zone_lookup.csv into purwadika.jcdeol3_capstone3_hafizh.taxi_zone
[2025-05-21T15:06:27.368+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:06:27.364+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taxi_data_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taxi_data_loader.py", line 28, in <module>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-05-21T15:06:27.369+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:06:27.417+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taxi_data_loader.py took 4.037 seconds
[2025-05-21T15:06:57.648+0000] {processor.py:186} INFO - Started process (PID=242) to work on /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:06:57.649+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taxi_data_loader.py for tasks to queue
[2025-05-21T15:06:57.650+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:06:57.650+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:07:02.047+0000] {logging_mixin.py:190} INFO - ✅ Loaded gs://jdeol003-bucket/capstone3_hafizh/taxi_zone_lookup.csv into purwadika.jcdeol3_capstone3_hafizh.taxi_zone
[2025-05-21T15:07:02.052+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:07:02.048+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taxi_data_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taxi_data_loader.py", line 28, in <module>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-05-21T15:07:02.053+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:07:02.069+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taxi_data_loader.py took 4.426 seconds
[2025-05-21T15:07:32.884+0000] {processor.py:186} INFO - Started process (PID=253) to work on /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:07:32.884+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taxi_data_loader.py for tasks to queue
[2025-05-21T15:07:32.885+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:07:32.885+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:07:36.969+0000] {logging_mixin.py:190} INFO - ✅ Loaded gs://jdeol003-bucket/capstone3_hafizh/taxi_zone_lookup.csv into purwadika.jcdeol3_capstone3_hafizh.taxi_zone
[2025-05-21T15:07:36.974+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:07:36.970+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taxi_data_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taxi_data_loader.py", line 28, in <module>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-05-21T15:07:36.974+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:07:36.990+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taxi_data_loader.py took 4.111 seconds
[2025-05-21T15:08:07.234+0000] {processor.py:186} INFO - Started process (PID=270) to work on /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:08:07.234+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taxi_data_loader.py for tasks to queue
[2025-05-21T15:08:07.235+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:08:07.235+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:08:11.704+0000] {logging_mixin.py:190} INFO - ✅ Loaded gs://jdeol003-bucket/capstone3_hafizh/taxi_zone_lookup.csv into purwadika.jcdeol3_capstone3_hafizh.taxi_zone
[2025-05-21T15:08:11.710+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:08:11.705+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taxi_data_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taxi_data_loader.py", line 28, in <module>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-05-21T15:08:11.710+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:08:11.752+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taxi_data_loader.py took 4.523 seconds
[2025-05-21T15:08:41.837+0000] {processor.py:186} INFO - Started process (PID=284) to work on /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:08:41.838+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taxi_data_loader.py for tasks to queue
[2025-05-21T15:08:41.839+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:08:41.839+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:08:45.607+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:08:45.606+0000] {process_utils.py:266} INFO - Waiting up to 5 seconds for processes to exit...
[2025-05-21T15:10:04.854+0000] {processor.py:186} INFO - Started process (PID=56) to work on /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:10:04.855+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taxi_data_loader.py for tasks to queue
[2025-05-21T15:10:04.857+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:10:04.857+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:10:09.585+0000] {logging_mixin.py:190} INFO - ✅ Loaded gs://jdeol003-bucket/capstone3_hafizh/taxi_zone_lookup.csv into purwadika.jcdeol3_capstone3_hafizh.taxi_zone
[2025-05-21T15:10:09.590+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:10:09.586+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taxi_data_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taxi_data_loader.py", line 28, in <module>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-05-21T15:10:09.591+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:10:09.637+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taxi_data_loader.py took 4.790 seconds
[2025-05-21T15:10:39.833+0000] {processor.py:186} INFO - Started process (PID=76) to work on /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:10:39.833+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taxi_data_loader.py for tasks to queue
[2025-05-21T15:10:39.835+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:10:39.835+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:10:43.720+0000] {logging_mixin.py:190} INFO - ✅ Loaded gs://jdeol003-bucket/capstone3_hafizh/taxi_zone_lookup.csv into purwadika.jcdeol3_capstone3_hafizh.taxi_zone
[2025-05-21T15:10:43.725+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:10:43.721+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taxi_data_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taxi_data_loader.py", line 28, in <module>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-05-21T15:10:43.725+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:10:43.761+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taxi_data_loader.py took 3.932 seconds
[2025-05-21T15:11:14.104+0000] {processor.py:186} INFO - Started process (PID=87) to work on /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:11:14.105+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taxi_data_loader.py for tasks to queue
[2025-05-21T15:11:14.106+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:11:14.106+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:11:18.463+0000] {logging_mixin.py:190} INFO - ✅ Loaded gs://jdeol003-bucket/capstone3_hafizh/taxi_zone_lookup.csv into purwadika.jcdeol3_capstone3_hafizh.taxi_zone
[2025-05-21T15:11:18.472+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:11:18.465+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taxi_data_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taxi_data_loader.py", line 28, in <module>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-05-21T15:11:18.473+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:11:18.511+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taxi_data_loader.py took 4.411 seconds
[2025-05-21T15:11:48.960+0000] {processor.py:186} INFO - Started process (PID=98) to work on /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:11:48.961+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taxi_data_loader.py for tasks to queue
[2025-05-21T15:11:48.962+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:11:48.962+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:11:52.731+0000] {logging_mixin.py:190} INFO - ✅ Loaded gs://jdeol003-bucket/capstone3_hafizh/taxi_zone_lookup.csv into purwadika.jcdeol3_capstone3_hafizh.taxi_zone
[2025-05-21T15:11:52.736+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:11:52.732+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taxi_data_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taxi_data_loader.py", line 28, in <module>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-05-21T15:11:52.737+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:11:52.753+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taxi_data_loader.py took 3.797 seconds
[2025-05-21T15:12:23.282+0000] {processor.py:186} INFO - Started process (PID=109) to work on /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:12:23.283+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taxi_data_loader.py for tasks to queue
[2025-05-21T15:12:23.286+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:12:23.286+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:12:26.979+0000] {logging_mixin.py:190} INFO - ✅ Loaded gs://jdeol003-bucket/capstone3_hafizh/taxi_zone_lookup.csv into purwadika.jcdeol3_capstone3_hafizh.taxi_zone
[2025-05-21T15:12:26.986+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:12:26.980+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taxi_data_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taxi_data_loader.py", line 28, in <module>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-05-21T15:12:26.986+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:12:27.006+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taxi_data_loader.py took 3.728 seconds
[2025-05-21T15:12:57.081+0000] {processor.py:186} INFO - Started process (PID=120) to work on /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:12:57.082+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taxi_data_loader.py for tasks to queue
[2025-05-21T15:12:57.083+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:12:57.083+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:13:01.233+0000] {logging_mixin.py:190} INFO - ✅ Loaded gs://jdeol003-bucket/capstone3_hafizh/taxi_zone_lookup.csv into purwadika.jcdeol3_capstone3_hafizh.taxi_zone
[2025-05-21T15:13:01.238+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:13:01.234+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taxi_data_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taxi_data_loader.py", line 28, in <module>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-05-21T15:13:01.239+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:13:01.255+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taxi_data_loader.py took 4.180 seconds
[2025-05-21T15:13:31.468+0000] {processor.py:186} INFO - Started process (PID=131) to work on /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:13:31.469+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_taxi_data_loader.py for tasks to queue
[2025-05-21T15:13:31.471+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:13:31.471+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:13:35.358+0000] {logging_mixin.py:190} INFO - ✅ Loaded gs://jdeol003-bucket/capstone3_hafizh/taxi_zone_lookup.csv into purwadika.jcdeol3_capstone3_hafizh.taxi_zone
[2025-05-21T15:13:35.363+0000] {logging_mixin.py:190} INFO - [2025-05-21T15:13:35.359+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_taxi_data_loader.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_taxi_data_loader.py", line 28, in <module>
    PythonOperator(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 508, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 224, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2025-05-21T15:13:35.364+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_taxi_data_loader.py
[2025-05-21T15:13:35.418+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_taxi_data_loader.py took 3.953 seconds
